#loading the data set, printing the first few rows to make sure it worked and see the data

In [1]:
import pandas as pd

url = "https://drive.google.com/uc?export=download&id=1O7Cqs2rK27s1Gqi3pmkJpYtXnc4tQphc"
df = pd.read_csv(url, encoding="latin1", low_memory=False)

df.head()

    Sentence #           Word  POS Tag
0  Sentence: 1      Thousands  NNS   O
1          NaN             of   IN   O
2          NaN  demonstrators  NNS   O
3          NaN           have  VBP   O
4          NaN        marched  VBN   O

In [2]:
#checking the column names so the code is accurate
df.columns

Index(['Sentence #', 'Word', 'POS', 'Tag'], dtype='object')

#all the pieces of the data frame are saved into sentences. each word in the sentence, with its pos and tag is grouped and saved until a new sentence is started.

In [11]:
sentences = []
current_sentence = []

for _, row in df.iterrows():
    if isinstance(row['Sentence #'], str) and row['Sentence #'].startswith("Sentence:"):
        if current_sentence:
            sentences.append(current_sentence)
            current_sentence = []
    current_sentence.append((row['Word'], row['POS'], row['Tag']))

# Add last sentence
if current_sentence:
    sentences.append(current_sentence)

In [12]:
df.head()

    Sentence #           Word  POS Tag
0  Sentence: 1      Thousands  NNS   O
1          NaN             of   IN   O
2          NaN  demonstrators  NNS   O
3          NaN           have  VBP   O
4          NaN        marched  VBN   O

###looking for all unique/possible tags

In [13]:
df["Tag"].unique()

array(['O', 'B-geo', 'B-gpe', 'B-per', 'I-geo', 'B-org', 'I-org', 'B-tim',
       'B-art', 'I-art', 'I-per', 'I-gpe', 'I-tim', 'B-nat', 'B-eve',
       'I-eve', 'I-nat'], dtype=object)

The following cell takes in the sentences and creates a dictionary about the information regarding each word and the previous and next word. it also includes information about special markers for beginning and end of sentences. This information is used to train the CRF model.

In [16]:
def word2features(sent, i):
    word = sent[i][0]
    postag = sent[i][1]
    word = str(word)

    features = {
        "bias": 1.0,
        "word.lower()": word.lower(),
        "word.isupper()": word.isupper(),
        "word.istitle()": word.istitle(),
        "word.isdigit()": word.isdigit(),
        "postag": postag,
        "postag[:2]": postag[:2],
    }

    if i > 0:
        word1 = str(sent[i-1][0])
        postag1 = sent[i-1][1]
        features.update({
            "-1:word.lower()": word1.lower(),
            "-1:word.istitle()": word1.istitle(),
            "-1:word.isupper()": word1.isupper(),
            "-1:postag": postag1,
            "-1:postag[:2]": postag1[:2],
        })
    else:
        features["BOS"] = True

    if i < len(sent)-1:
        word1 = str(sent[i+1][0])
        postag1 = sent[i+1][1]
        features.update({
            "+1:word.lower()": word1.lower(),
            "+1:word.istitle()": word1.istitle(),
            "+1:word.isupper()": word1.isupper(),
            "+1:postag": postag1,
            "+1:postag[:2]": postag1[:2],
        })
    else:
        features["EOS"] = True

    return features


def sent2features(sent):
    return [word2features(sent, i) for i in range(len(sent))]


def sent2labels(sent):
    return [label for (_, _, label) in sent]

splitting the data into 80%-20% train and test data.

In [19]:
from sklearn.model_selection import train_test_split

X = [sent2features(s) for s in sentences]
y = [sent2labels(s) for s in sentences]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

Training and creating the crf model. I set the words training is complete to notify when the training is complete.

In [20]:
!pip install sklearn-crfsuite
import sklearn_crfsuite

crf = sklearn_crfsuite.CRF(
    algorithm="lbfgs",
    c1=0.1,
    c2=0.1,
    max_iterations=100,
    all_possible_transitions=True,
)

print("Training CRF model... this may take a few minutes.")
crf.fit(X_train, y_train)
print("Training complete.")

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: sklearn-crfsuite in ./.local/lib/python3.12/site-packages (0.5.0)
Requirement already satisfied: python-crfsuite>=0.9.7 in ./.local/lib/python3.12/site-packages (from sklearn-crfsuite) (0.9.12)
Requirement already satisfied: scikit-learn>=0.24.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from sklearn-crfsuite) (1.7.2)
Requirement already satisfied: tabulate>=0.4.2 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from sklearn-crfsuite) (0.9.0)
Requirement already satisfied: tqdm>=2.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from sklearn-crfsuite) (4.67.1)
Requirement already satisfied: numpy>=1.22.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from scikit-learn>=0.24.0->sklearn-crfsuite) (1.26.4)
Requirement already satisfied: scipy>=1.8.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from scikit-learn>=0.24.0->sklearn-crfsuite) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from scikit-learn>=0.24.0->sklearn-crfsuite) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from scikit-learn>=0.24.0->sklearn-crfsuite) (3.5.0)
Training CRF model... this may take a few minutes.
Training complete.

Model evaluation

In [21]:
from sklearn_crfsuite import metrics

y_pred = crf.predict(X_test)

print("Model Evaluation:")
print(metrics.flat_classification_report(y_test, y_pred))

Model Evaluation:
              precision    recall  f1-score   support

       B-art       0.35      0.14      0.20        86
       B-eve       0.46      0.30      0.36        60
       B-geo       0.86      0.91      0.88      7664
       B-gpe       0.97      0.94      0.95      3175
       B-nat       0.62      0.32      0.42        50
       B-org       0.80      0.74      0.77      3913
       B-per       0.84      0.83      0.84      3389
       B-tim       0.93      0.88      0.90      4049
       I-art       0.04      0.02      0.02        58
       I-eve       0.42      0.25      0.31        53
       I-geo       0.82      0.79      0.80      1450
       I-gpe       0.80      0.62      0.70        39
       I-nat       0.44      0.33      0.38        12
       I-org       0.83      0.80      0.82      3315
       I-per       0.85      0.91      0.88      3445
       I-tim       0.83      0.77      0.79      1300
           O       0.99      0.99      0.99    176877

    accuracy                           0.97    208935
   macro avg       0.70      0.62      0.65    208935
weighted avg       0.97      0.97      0.97    208935

Installing spacy

In [22]:
!pip install spacy
!python -m spacy download en_core_web_sm

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: spacy in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (3.7.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (1.0.4)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.1.8 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (8.2.2)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.4.0,>=0.1.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (0.3.4)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (0.9.0)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (5.2.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (4.67.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (2.12.4)
Requirement already satisfied: jinja2 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (3.5.0)
Requirement already satisfied: numpy>=1.19.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy) (1.26.4)
Requirement already satisfied: language-data>=1.2 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.11.12)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from thinc<8.3.0,>=8.1.8->spacy) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from thinc<8.3.0,>=8.1.8->spacy) (0.1.5)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from typer<0.10.0,>=0.3.0->spacy) (8.1.8)
Requirement already satisfied: cloudpathlib<0.17.0,>=0.7.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from weasel<0.4.0,>=0.1.0->spacy) (0.16.0)
Requirement already satisfied: marisa-trie>=1.1.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from jinja2->spacy) (3.0.2)
Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Collecting en-core-web-sm==3.7.1
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 70.9 MB/s  0:00:0073.4 MB/s eta 0:00:01
Requirement already satisfied: spacy<3.8.0,>=3.7.2 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from en-core-web-sm==3.7.1) (3.7.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.0.4)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.1.8 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (8.2.2)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.0.10)
Requirement already satisfied: weasel<0.4.0,>=0.1.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.3.4)
Requirement already satisfied: typer<0.10.0,>=0.3.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.9.0)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (5.2.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (4.67.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.12.4)
Requirement already satisfied: jinja2 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.1.6)
Requirement already satisfied: setuptools in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (80.9.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.5.0)
Requirement already satisfied: numpy>=1.19.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.26.4)
Requirement already satisfied: language-data>=1.2 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.local/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2025.11.12)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from thinc<8.3.0,>=8.1.8->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from thinc<8.3.0,>=8.1.8->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.1.5)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from typer<0.10.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (8.1.8)
Requirement already satisfied: cloudpathlib<0.17.0,>=0.7.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from weasel<0.4.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.16.0)
Requirement already satisfied: marisa-trie>=1.1.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/envs/anaconda-ai-2025.12-py312/lib/python3.12/site-packages (from jinja2->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.0.2)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

Importing the spacy model

In [23]:
import spacy
nlp = spacy.load("en_core_web_sm")

Running the sentence through the spacy model. This model detects and prints all the named entities.

In [24]:
sentence = "Fourteen days ago, Emperor Palpatine left San Diego, CA for Tatooine to follow Luke Skywalker."
doc = nlp(sentence)

for ent in doc.ents:
    print(ent.text, ent.label_)

Fourteen days ago DATE
Palpatine PERSON
San Diego GPE
CA WORK_OF_ART
Tatooine PERSON
Luke Skywalker PERSON

We are running the same sentence through the Ner, CRf pipeline that was created a few cells back

In [25]:
import nltk
from nltk import word_tokenize, pos_tag

sentence = "Fourteen days ago, Emperor Palpatine left San Diego, CA for Tatooine to follow Luke Skywalker."

# Tokenize and POS-tag
tokens = word_tokenize(sentence)
pos_tags = pos_tag(tokens)

# Convert to CRF feature format
test_sent = [(word, pos, 'O') for word, pos in pos_tags]  # dummy tags
X_test_sent = [sent2features(test_sent)]

# Predict
y_pred_sent = crf.predict(X_test_sent)[0]

# Display results
for word, tag in zip(tokens, y_pred_sent):
    print(f"{word:15} {tag}")

Fourteen        B-org
days            O
ago             O
,               O
Emperor         B-per
Palpatine       I-per
left            O
San             B-geo
Diego           I-geo
,               O
CA              B-org
for             I-org
Tatooine        I-org
to              O
follow          O
Luke            B-org
Skywalker       I-org
.               O

Evaluating this model

In [26]:
from sklearn_crfsuite import metrics

labels = list(crf.classes_)
labels.remove('O')

y_pred = crf.predict(X_test)

print(metrics.flat_classification_report(y_test, y_pred, labels=labels))

              precision    recall  f1-score   support

       B-gpe       0.97      0.94      0.95      3175
       B-geo       0.86      0.91      0.88      7664
       B-org       0.80      0.74      0.77      3913
       I-org       0.83      0.80      0.82      3315
       I-geo       0.82      0.79      0.80      1450
       B-tim       0.93      0.88      0.90      4049
       B-per       0.84      0.83      0.84      3389
       I-per       0.85      0.91      0.88      3445
       B-eve       0.46      0.30      0.36        60
       I-eve       0.42      0.25      0.31        53
       I-tim       0.83      0.77      0.79      1300
       B-nat       0.62      0.32      0.42        50
       I-nat       0.44      0.33      0.38        12
       I-gpe       0.80      0.62      0.70        39
       B-art       0.35      0.14      0.20        86
       I-art       0.04      0.02      0.02        58

   micro avg       0.86      0.85      0.86     32058
   macro avg       0.68      0.60      0.63     32058
weighted avg       0.86      0.85      0.85     32058

Compare the spacy model to the homemade CRF model


At first the scores on the top of the spacy model were a lot lower than the scores of the crf, but that isn't necessarily the best place to get the overall accuracy and precision score. The f1-score is the most important because it is the accuracy and precision combined. The micro f1 score is the average f1 score but all entities have the same weight so i doesn't show the most precise information. The macro fi-score is fair across all entity types. either way the spacy model scored higher, at .97 and .65 as apposed to .86 and .63. The macro avg of the f1 scores are only 2% off, which isn't such a big difference.